version: '2'

services:
  fpm:
    image: akeneo/php:7.2
    environment:
      COMPOSER_HOME: /home/docker/.composer
    user: docker
    volumes:
      - ./:/srv/pim
      - ~/.composer:/home/docker/.composer
    working_dir: /srv/pim
    networks:
      - akeneo

networks:
  akeneo: ~
